### ISSUE TITLE
NYPL & BPL max length of a vendor code

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/babel#39]
What's maximum number of characters a vendor code can have in Sierra, @Mfgloger ?

**Comment by Mfgloger** [comment]
5 characters
[Sierra - Variable-length Fields in Vendor Records.pdf](https://github.com/BookOps-CAT/babel/files/3424134/Sierra.-.Variable-length.Fields.in.Vendor.Records.pdf)

**Comment by klinga** [comment]
thanks!
