### ISSUE TITLE
Test resource editing functionality

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/babel#48]
Test the resource editing widget in the cart (after validation is added #46)

**Comment by Mfgloger** [comment]
I couldn't get the interface to do anything odd, however:
It does lets me edit and remove records after the cart is finalized.
It does let me change prices (which changes the calculated funds) after the cart is finalized.

**Comment by klinga** [comment]
I think allowing users to change finalized cart is fine, but we should watch how this functionality is used. Finalizing a cart meant to be a safeguard against producing incomplete MARC records. It validates the cart and gives user a pause to think if data is complete.
