### ISSUE TITLE
Max length of a fund code

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/babel#59]
@Mfgloger, would you be able to pull from Sierra docs max length of a fund code?
Needed for the FundView entry box validation.
Thanks!

**Comment by Mfgloger** [comment]
This is from the funds codes table or order record 012 field? (same character number)

https://csdirect.iii.com/sierrahelp/Content/sgacq/sgacq_funds_fields.html

CODE | System-wide identification code for the library fund. The code cannot be edited after the fund is created. | Up to 15 characters. The code must use only lowercase alphabetic or numeric characters.
-- | -- | --

https://csdirect.iii.com/sierrahelp/Content/sril/sril_records_fixed_field_types_order.html#ACQ%20TYPE
012 | FUND or Fund | Fund against which the material will be encumbered and paid. (For multiple funds, see the variable-length field FUNDS.) | lowercase alphabetic or numeric characters. | organization | Maximum code length: 15 charactersMaximum length of code definitions: 19 characters The maximum number of fund codes allowed in a single order record is 100. Maximum number of codes: Up to 5000.
